Rc2.0 methodtime
fpsim/fpsim pull request #411
Opened 2024-09-25 20:12 UTC by emilydriano

### Brief description
[add description here, including any linked issues]

### Type(s) of change
- [ ] Bugfix
- [ X ] Refactor
- [ X ] New feature
- [ ] Other

### Checklist
- My code follows the [style guide](https://github.com/amath-idm/styleguide)
  - [ X ] Yes
  - [ ] N/A
- I've commented my code
  - [ X ] Yes
  - [ ] N/A
- I've incremented the version number
  - [ ] Yes
  - [ ] N/A
- I've updated the changelog
  - [ ] Yes
  - [ ] N/A
- I've added tests and checked code coverage
  - [ X] Yes
  - [ ] N/A

2024-09-25 21:28 UTC, cliffckerr requested changes
I would prefer not to make `starsim` a dependency of FPsim just to use `ss.ndict`. To me it looks weird that when you import FPsim, it now prints the Starsim copyright. I'd prefer to either (a) copy the `ndict` code into FPsim, or (b) I can move `ss.ndict` to Sciris (https://github.com/sciris/sciris/issues/616). Let me know if you want me to do the latter.

2024-10-08 18:26 UTC, emilydriano commented
> I would prefer not to make `starsim` a dependency of FPsim just to use `ss.ndict`. To me it looks weird that when you import FPsim, it now prints the Starsim copyright. I'd prefer to either (a) copy the `ndict` code into FPsim, or (b) I can move `ss.ndict` to Sciris ([sciris/sciris#616](https://github.com/sciris/sciris/issues/616)). Let me know if you want me to do the latter.

@robynstuart

2025-04-08 20:31 UTC, MObrien-IDM commented on docs/tutorials/T1_intro.ipynb
> +    "```\n",
Once this is released then people can use pip install fpsim, right?

2025-04-09 16:31 UTC, MObrien-IDM commented on fpsim/locations/kenya/process_durations_lnorm.py
> +Investigating durations
Note for me to return to this - documentation can be better here

2025-04-09 21:16 UTC, MObrien-IDM commented on fpsim/scenarios.py
Seems like this particular script has lost quite a bit of documentation. Noting for myself to return to later.

2025-04-09 21:17 UTC, MObrien-IDM commented on fpsim/settings.py
>  __all__ = ['options']
What does "visible things" mean? @robynstuart @emilydriano

2025-04-09 21:24 UTC, MObrien-IDM commented on tests/devtest_sim.py
> +"""
Note to improve documentation here

2025-04-09 21:28 UTC, MObrien-IDM commented on tests/test_integration.py
> +"""
List components in documentation. (Note for myself for Documentation Overhaul)

2025-04-09 21:32 UTC, MObrien-IDM commented on docs/tutorials/T1_intro.ipynb
>      "\n",
@emilydriano Let's change these references to the branch (below) because after we merge (SOON), we can just have folks pip install fpsim.

2025-04-10 19:04 UTC, mzimmermann-IDM commented on fpsim/locations/kenya/kenya.py
>      files['methods'] = 'mix.csv'
@emilydriano can you help me with a question? I see that mix.csv is called here, which looks like it's just an array with a percentage for each method. We should be using method_mix_matrix_switch.csv, which has different arrays depending on postpartum, previous method, and age. Is that implemented somewhere else and I'm missing it?? I know in a previous version the percentages ere hard coded rather than reading in the csv, so maybe that's happening somewhere and I can't find it?

2025-04-10 20:25 UTC, emilydriano commented on fpsim/locations/kenya/kenya.py
>      files['methods'] = 'mix.csv'
@mzimmermann-IDM yes, so method_mix_matrix_switch.csv is indeed being used but isn't referenced directly in kenya.py... it's used in the function process_markovian_method_choice (which is in data_utils.py) which is then called in init_method_pars in methods.py. The file mix.csv is only being used for calibration (comparing the method mix at the end of the sim to the values in the 'mix' file).

2025-04-10 23:32 UTC, mzimmermann-IDM commented on fpsim/locations/kenya/kenya.py
>      files['methods'] = 'mix.csv'
Ok great, thanks @emilydriano ! I was looking at the relevant to tutorial 3 where you can update the method mix. In the intervention, method mix is replaces with a single array so I was trying to figure out how it works. Does it replace all of the different arrays in the matrices from the csv with the user defined array? I think that must be what's happening but can you confirm? 

The other thing I can't find explicitly documented is the order of the methods. I assume it is alphabetical as it is in the csv's, but would be great to confirm (and include very clearly in all the documentation @MObrien-IDM )

2025-04-11 15:50 UTC, emilydriano commented on fpsim/locations/kenya/kenya.py
>      files['methods'] = 'mix.csv'
Good question.. so this intervention sets the probabilities of methods being selected by modifying the contraceptive module's pars['method_mix'], which normally by default sets all methods to having equal probability of being chosen (i.e. with 9 methods, each has prob of ~0.111). But it looks like this param is only being used in the RandomChoice module and not the Simple or Standard choice ones.. @robynstuart can you confirm? 
![image](https://github.com/user-attachments/assets/e9179309-2826-46a5-9e52-fe81f07951b5)

The method mix order is the same as those in the 'method_list' in methods.py, starting with 'pill': 
![image](https://github.com/user-attachments/assets/39b8f786-c53f-47a7-9e2e-0f263110d873)

2025-04-11 17:34 UTC, mzimmermann-IDM commented
@MObrien-IDM tutorials are cleaned up!

2025-04-11 18:09 UTC, MObrien-IDM approved these changes

2025-04-11 19:29 UTC, cliffckerr approved these changes
🎆

2025-04-11 19:30 UTC, merged